mirror:
  stage: build
  image: buildpack-deps:xenial-scm
  script:
    - git push -q --prune https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/NERC-CEH/ubuntu.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
